#!/usr/bin/env node
import { Command } from 'commander'
import { syncToProject } from './lib/index.js'

const program = new Command()

program
  .name('oss-project-tracker')
  .description('Sync GitHub issues and pull requests from an organization to a project board')
  .version('1.0.0')

program
  .command('sync-to-project')
  .description('Sync GitHub issues/pull requests from organization to project board')
  .argument('<org>', 'GitHub organization name')
  .argument('<project-number>', 'Project number (e.g., 12) of project within organization')
  .action(async (org, projectNumber) => {
    await syncToProject(org, projectNumber)
  })

program.parse()
